title: "Rita Okonkwo"
email: fellowship@mlh.io
description: >- # this means to ignore newlines until "baseurl:"
  Rita Okonkwo portfolio
baseurl: "/" 
url: "/ritaokonkwo" 
github_username:  Rita-Okonkwo

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
